### PR TITLE
Respect disable_settings_management, fixes #6

### LINKED ISSUE #6: Respect the disable_settings_management flag for settings.redis.php
Thanks for adding the settings for redis!  that is a great way to get bootstrapped up with reasonable defaults.

Though sometimes it's nice to leave those up to the project! Let's respect the `disable_settings_management` flag and not add the `settings.redis.php` if that configuration is enabled.

### PR DESCRIPTION
**Pull request by joelpittet**
* #6

### CODE REVIEW

**Review by rfay — COMMENTED** [review]
I haven't manually tested this, but it seems like a reasonable approach. Seems like `ddev debug configyaml` could also be more usable as well, but this seems like a good approach.

**Review by rfay — CHANGES_REQUESTED** [review]
IMO this is working great, checked it manually, seems right. The only thing is the extra output seems confusing:

```
rfay@rfay-mbp-2021:~/workspace/junk$ ddev get ../ddev-redis/
Installed file /Users/rfay/workspace/junk/.ddev/docker-compose.redis.yaml
Installed file /Users/rfay/workspace/junk/.ddev/redis/scripts/settings.ddev.redis.php
Installed file /Users/rfay/workspace/junk/.ddev/redis/scripts/setup-drupal-settings.sh
Installed file /Users/rfay/workspace/junk/.ddev/redis/redis.conf
Installed file /Users/rfay/workspace/junk/.ddev/commands/redis/redis-cli
Not creating settings.ddev.redis.php because disable_settings_management=true

Executed action 'set -eu -o pipefail
redis/scripts/setup-drupal-settings.sh', output='Not creating settings.ddev.redis.php because disable_settings_management=true
'
```

It properly does everything, it's just that we've already seen that output "Not creating settings.ddev.php" from the script, and then we see

```
Executed action 'set -eu -o pipefail
redis/scripts/setup-drupal-settings.sh', output='Not creating settings.ddev.redis.php because disable_settings_management=true
'
```

Is there a way around this?

**Comment by hussainweb** [comment]
The changes look good to me too. I agree about the output being confusing but it is no more confusing than many commands that report error twice. Yes, I wish it didn't happen but I can't think of a way to echo and not echo at the same time. :)

I am also thinking if this line is strictly required. Do other commands report such a message when `disable_settings_management` is `true`?

**Comment by joelpittet** [comment]
DDEV already tells the user about this, so maybe that would suffice and we can just `exit 0`? I'll push that change in here

**Review by rfay — APPROVED** [review]
This seems reasonable to me.

**Comment by rfay** [comment]
Tested with `ddev get https://github.com/joelpittet/ddev-redis/tarball/main` and it behaved as expected with disable_settings_management=true.  Then turned it off and made sure the existing settings were removed and did the get again and it worked as expected, created settings.

@hussainweb I'm fine with this when you are. Thanks @joelpittet !

**Review by hussainweb — APPROVED** [review]

**Comment by hussainweb** [comment]
I agree with you @rfay and merging it. I'll leave it up to you to check if you'd want to create a release for this change. I think it's worth creating a new release because it aligns with how DDEV handles settings.

**Comment by rfay** [comment]
Yes, needs a release. Probably anything that alters behavior needs a release; only tests or README changes don't. Thanks!

**Pull request merged**
